version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        user: crypto
        uid: 1000
    container_name: crypto-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - crypto-network

  nginx:
    image: nginx:alpine
    container_name: crypto-nginx
    restart: unless-stopped
    ports:
      - "13579:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - crypto-network
    depends_on:
      - app

  reverb:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        user: crypto
        uid: 1000
    container_name: crypto-reverb
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www
    environment:
      - REVERB_SERVER_HOST=0.0.0.0
      - REVERB_SERVER_PORT=8080
      - REVERB_APP_ID=${REVERB_APP_ID}
      - REVERB_APP_KEY=${REVERB_APP_KEY}
    networks:
      - crypto-network
    command: php /var/www/artisan reverb:start

  supervisor:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        user: crypto
        uid: 1000
    container_name: crypto-supervisor
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/supervisor/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf
      - ./docker/startup.sh:/startup.sh
    networks:
      - crypto-network
    depends_on:
      - app
      - reverb
    command: bash /startup.sh
    user: root

networks:
  crypto-network:
    driver: bridge